### check healthcheck
GET   http://localhost:1337/healthcheck

### get all user 
GET   http://localhost:1337/api/users

### get unique user 
GET   http://localhost:1337/api/users/628a51f80208b96488eec815


### creat a user 
POST http://localhost:1337/api/user
Content-Type: application/json

{ "name":"myname",
  "email":"myname@email.com",
  "password" : "123456",
  "passwordConfirmation":"123456"
}


### Get Logedin Session
GET    http://localhost:1337/api/sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjhhNTFmODAyMDhiOTY0ODhlZWM4MTUiLCJlbWFpbCI6Im15bmFtZUBlbWFpbC5jb20iLCJuYW1lIjoibXluYW1lIiwiY3JlYXRlZEF0IjoiMjAyMi0wNS0yMlQxNTowODo0MC40NTlaIiwidXBkYXRlZEF0IjoiMjAyMi0wNS0yMlQxNTowODo0MC40NTlaIiwiX192IjowLCJzZXNzaW9uIjoiNjI4YTU3NTBhMzFkZDk0Y2RjYjg2ZDViIiwiaWF0IjoxNjUzMjMzNDg5LCJleHAiOjE2NTMyMzQzODl9.7RwZmcrGWUbjnrCIq4m1qf0cOkoOXQbu1Nh4YMXqgz0
x-refersh :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjI4YTUxZjgwMjA4Yjk2NDg4ZWVjODE1IiwidmFsaWQiOnRydWUsInVzZXJBZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50IiwiX2lkIjoiNjI4YTU3NTBhMzFkZDk0Y2RjYjg2ZDViIiwiY3JlYXRlZEF0IjoiMjAyMi0wNS0yMlQxNTozMToyOC45NTVaIiwidXBkYXRlZEF0IjoiMjAyMi0wNS0yMlQxNTozMToyOC45NTVaIiwiX192IjowLCJpYXQiOjE2NTMyMzM0ODksImV4cCI6MTY4NDc5MTA4OX0.X9scP_OA2cmKNky9u6kfFizC5P316USqQBKu2pnI18I

### Login funcctionality  
POST   http://localhost:1337/api/sessions
Content-Type: application/json

{
    "password" : "123456",
     "email": "myname@email.com"
}

### Logout functionality 
DELETE http://localhost:1337/api/sessions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjhhNTFmODAyMDhiOTY0ODhlZWM4MTUiLCJlbWFpbCI6Im15bmFtZUBlbWFpbC5jb20iLCJuYW1lIjoibXluYW1lIiwiY3JlYXRlZEF0IjoiMjAyMi0wNS0yMlQxNTowODo0MC40NTlaIiwidXBkYXRlZEF0IjoiMjAyMi0wNS0yMlQxNTowODo0MC40NTlaIiwiX192IjowLCJzZXNzaW9uIjoiNjI4YTU3NTBhMzFkZDk0Y2RjYjg2ZDViIiwiaWF0IjoxNjUzMjMzNDg5LCJleHAiOjE2NTMyMzQzODl9.7RwZmcrGWUbjnrCIq4m1qf0cOkoOXQbu1Nh4YMXqgz0
x-refersh :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjI4YTUxZjgwMjA4Yjk2NDg4ZWVjODE1IiwidmFsaWQiOnRydWUsInVzZXJBZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50IiwiX2lkIjoiNjI4YTU3NTBhMzFkZDk0Y2RjYjg2ZDViIiwiY3JlYXRlZEF0IjoiMjAyMi0wNS0yMlQxNTozMToyOC45NTVaIiwidXBkYXRlZEF0IjoiMjAyMi0wNS0yMlQxNTozMToyOC45NTVaIiwiX192IjowLCJpYXQiOjE2NTMyMzM0ODksImV4cCI6MTY4NDc5MTA4OX0.X9scP_OA2cmKNky9u6kfFizC5P316USqQBKu2pnI18I

{
  "email": "myname@email.com",
  "password" : "123456"
}
